swagger: "2.0"
info:
  description: "Test api from task from internet"
  version: "0.0.1"
  title: "Swagger API"
  contact:
    email: "echodiv@outlook.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
paths:
  /tasks:
    post:
      summary: "Create new task"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Task"
        "400":
          description: "Invalid data"
    get:
      summary: "Get all tasks"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Task"
  /tags:
    post:
      summary: "Create new tag"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Tag"
        "400":
          description: "Invalid data"
    get:
      summary: "Get tag and all tags"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Tag"

  /tasks/{taskId}:
    get:
      summary: "Get task with taskId"
      produces:
      - "application/json"    
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Task"
        "404":
          description: "task not found"
  /tags/{tagId}:
    get:
      summary: "Get tag by tagId and all tasks with it"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Tag"
        "404":
          description: "tag not found"
definitions:
  Tag:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      date_of_creation:
        type: "string"
        format: "date-time"
      tasks:
        type: "array"
        items:
          $ref: "#/definitions/Task"
  Task:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      description:
        type: "string"
      date_of_creation:
        type: "string"
        format: "date-time"