version: '3.7'
services:
  db:
    image: postgres:12.0-alpine
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret12345
      - POSTGRES_DB=dev

volumes: 
    postgres_data: